package summary_test

import (
	"os"
	"testing"

	"github.com/andreyvit/diff"

	"github.com/yoanm/go-deps-diff/contract"

	summary "github.com/yoanm/go-deps-diff-summary"

	difftesting "github.com/yoanm/go-deps-diff/testing"
)

func TestIntegration_GenerateForChanges(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name       string
		changes    contract.DiffMap
		goldenFile string
	}{
		{
			name:       "Full",
			changes:    _integrationFullChanges,
			goldenFile: "./testdata/golden-full-summary.md",
		},
		{
			name:       "Special case - shortest table size - Table with only three column needed",
			changes:    _integrationOnlyThreeColumnsNeeded,
			goldenFile: "./testdata/golden-3columns-summary.md",
		},
		{
			name:       "Special case - force opened/closed details",
			changes:    _integrationForceOpenedClosed,
			goldenFile: "./testdata/golden-force_opened_details.md",
		},
	}
	for _, testCase := range tests {
		t.Run(testCase.name, func(t *testing.T) {
			t.Parallel()

			expected, err := os.ReadFile(testCase.goldenFile)
			if err != nil {
				t.Errorf("Diff() error while reading golden file = %v", err)

				return
			}

			current := summary.GenerateForChanges(testCase.changes, "MyManager")

			// fmt.Println("EXPECTED:" + string(expected))

			if string(expected) != current {
				t.Errorf("unexpected output: diff %s", diff.LineDiff(string(expected), current))
			}
		})
	}
}

var _integrationFullChanges = contract.DiffMap{
	"caution-dev_only_usage-requirement/ADDITION+ABANDONED": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "caution-dev_only_usage-requirement/ADDITION+ABANDONED",
			Abandoned:          true,
			Version:            contract.PkgVersion{Raw: "1.18.4", Label: "1.18.4", Semver: &contract.Semver{Major: 1, Minor: 18, Patch: 4, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            true,
			RootRequirement:    false,
			RootDevRequirement: true,
		},
		Operation: difftesting.AdditionOp,
	},
	"caution-dev_only_usage-requirement/SEMVER_MAJOR_DOWNGRADE": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "caution-dev_only_usage-requirement/SEMVER_MAJOR_DOWNGRADE",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "1.2.0", Label: "1.2.0", Semver: &contract.Semver{Major: 1, Minor: 2, Patch: 0, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            true,
			RootRequirement:    false,
			RootDevRequirement: true,
		},
		Operation:       difftesting.DowngradeMajorOp,
		PreviousVersion: contract.PkgVersion{Raw: "2.9.2", Label: "2.9.2", Semver: &contract.Semver{Major: 2, Minor: 9, Patch: 2, Extra: ""}},
	},
	"caution-dev_only_usage-requirement/UNKNOWN_UPDATE": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "caution-dev_only_usage-requirement/UNKNOWN_UPDATE",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "12345678", Label: "2.9.x-dev#1234567", Semver: nil},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            true,
			RootRequirement:    false,
			RootDevRequirement: true,
		},
		Operation:       difftesting.UnknownUpdateOp,
		PreviousVersion: contract.PkgVersion{Raw: "2acf168", Label: "2.9.x-dev#2acf168", Semver: nil},
	},
	"caution-dev_only_usage-requirement/UNKNOWN_UPDATE+SEMVER_EXTRA": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "caution-dev_only_usage-requirement/UNKNOWN_UPDATE+SEMVER_EXTRA",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "2.9.2+alpha", Label: "2.9.2+alpha", Semver: &contract.Semver{Major: 2, Minor: 9, Patch: 2, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            true,
			RootRequirement:    false,
			RootDevRequirement: true,
		},
		Operation:       difftesting.SemverExtraUpdateOp,
		PreviousVersion: contract.PkgVersion{Raw: "2.9.2+beta", Label: "2.9.2+beta", Semver: &contract.Semver{Major: 2, Minor: 9, Patch: 2, Extra: "+beta"}},
	},
	"caution-prod_usage-requirement+dev_req/ADDITION+ABANDONED": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "caution-prod_usage-requirement+dev_req/ADDITION+ABANDONED",
			Abandoned:          true,
			Version:            contract.PkgVersion{Raw: "1.18.4", Label: "1.18.4", Semver: &contract.Semver{Major: 1, Minor: 18, Patch: 4, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            false,
			RootRequirement:    false,
			RootDevRequirement: true,
		},
		Operation: difftesting.AdditionOp,
	},
	"caution-prod_usage-requirement+dev_req/SEMVER_MAJOR_DOWNGRADE": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "caution-prod_usage-requirement+dev_req/SEMVER_MAJOR_DOWNGRADE",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "1.18.4", Label: "1.18.4", Semver: &contract.Semver{Major: 1, Minor: 18, Patch: 4, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            false,
			RootRequirement:    false,
			RootDevRequirement: true,
		},
		Operation:       difftesting.DowngradeMajorOp,
		PreviousVersion: contract.PkgVersion{Raw: "2.9.2", Label: "2.9.2", Semver: &contract.Semver{Major: 2, Minor: 9, Patch: 2, Extra: ""}},
	},
	"caution-prod_usage-requirement+dev_req/UNKNOWN_UPDATE": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "caution-prod_usage-requirement+dev_req/UNKNOWN_UPDATE",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "12345678", Label: "2.9.x-dev#1234567", Semver: nil},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            false,
			RootRequirement:    false,
			RootDevRequirement: true,
		},
		Operation:       difftesting.UnknownUpdateOp,
		PreviousVersion: contract.PkgVersion{Raw: "2acf168", Label: "2.9.x-dev#2acf168", Semver: nil},
	},
	"caution-prod_usage-requirement+dev_req/UNKNOWN_UPDATE+SEMVER_EXTRA": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "caution-prod_usage-requirement+dev_req/UNKNOWN_UPDATE+SEMVER_EXTRA",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "2.9.2+alpha", Label: "2.9.2+alpha", Semver: &contract.Semver{Major: 2, Minor: 9, Patch: 2, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            false,
			RootRequirement:    false,
			RootDevRequirement: true,
		},
		Operation:       difftesting.SemverExtraUpdateOp,
		PreviousVersion: contract.PkgVersion{Raw: "2.9.2+beta", Label: "2.9.2+beta", Semver: &contract.Semver{Major: 2, Minor: 9, Patch: 2, Extra: "+beta"}},
	},
	"caution-prod_usage-requirement/ADDITION+ABANDONED": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "caution-prod_usage-requirement/ADDITION+ABANDONED",
			Abandoned:          true,
			Version:            contract.PkgVersion{Raw: "1.18.4", Label: "1.18.4", Semver: &contract.Semver{Major: 1, Minor: 18, Patch: 4, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            false,
			RootRequirement:    true,
			RootDevRequirement: false,
		},
		Operation: difftesting.AdditionOp,
	},
	"caution-prod_usage-requirement/SEMVER_MAJOR_DOWNGRADE": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "caution-prod_usage-requirement/SEMVER_MAJOR_DOWNGRADE",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "1.18.4", Label: "1.18.4", Semver: &contract.Semver{Major: 1, Minor: 18, Patch: 4, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            false,
			RootRequirement:    true,
			RootDevRequirement: false,
		},
		Operation:       difftesting.DowngradeMajorOp,
		PreviousVersion: contract.PkgVersion{Raw: "2.9.2", Label: "2.9.2", Semver: &contract.Semver{Major: 2, Minor: 9, Patch: 2, Extra: ""}},
	},
	"caution-prod_usage-requirement/UNKNOWN_UPDATE": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "caution-prod_usage-requirement/UNKNOWN_UPDATE",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "12345678", Label: "2.9.x-dev#1234567", Semver: nil},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            false,
			RootRequirement:    true,
			RootDevRequirement: false,
		},
		Operation:       difftesting.UnknownUpdateOp,
		PreviousVersion: contract.PkgVersion{Raw: "2acf168", Label: "2.9.x-dev#2acf168", Semver: nil},
	},
	"caution-prod_usage-requirement/UNKNOWN_UPDATE+SEMVER_EXTRA": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "caution-prod_usage-requirement/UNKNOWN_UPDATE+SEMVER_EXTRA",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "2.9.2+alpha", Label: "2.9.2+alpha", Semver: &contract.Semver{Major: 2, Minor: 9, Patch: 2, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            false,
			RootRequirement:    true,
			RootDevRequirement: false,
		},
		Operation:       difftesting.SemverExtraUpdateOp,
		PreviousVersion: contract.PkgVersion{Raw: "2.9.2+beta", Label: "2.9.2+beta", Semver: &contract.Semver{Major: 2, Minor: 9, Patch: 2, Extra: "+beta"}},
	},
	"warning-dev_only_usage-requirement/SEMVER_MAJOR_UPGRADE": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "warning-dev_only_usage-requirement/SEMVER_MAJOR_UPGRADE",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "3.0.0", Label: "3.0.0", Semver: &contract.Semver{Major: 3, Minor: 0, Patch: 0, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            true,
			RootRequirement:    false,
			RootDevRequirement: true,
		},
		Operation:       difftesting.UpgradeMajorOp,
		PreviousVersion: contract.PkgVersion{Raw: "2.9.3", Label: "2.9.3", Semver: &contract.Semver{Major: 2, Minor: 9, Patch: 3, Extra: ""}},
	},
	"warning-dev_only_usage-requirement/ADDITION_NOT_SEMVER": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "warning-dev_only_usage-requirement/ADDITION_NOT_SEMVER",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "abcdefghijk", Label: "dev-master#abcdefgh", Semver: nil},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            true,
			RootRequirement:    false,
			RootDevRequirement: true,
		},
		Operation: difftesting.AdditionOp,
	},
	"warning-dev_only_usage-requirement/SEMVER_MINOR_DOWNGRADE": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "warning-dev_only_usage-requirement/SEMVER_MINOR_DOWNGRADE",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "3.0.0", Label: "3.0.0", Semver: &contract.Semver{Major: 3, Minor: 0, Patch: 0, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            true,
			RootRequirement:    false,
			RootDevRequirement: true,
		},
		Operation:       difftesting.DowngradeMinorOp,
		PreviousVersion: contract.PkgVersion{Raw: "3.1.0", Label: "3.1.0", Semver: &contract.Semver{Major: 3, Minor: 1, Patch: 0, Extra: ""}},
	},
	"warning-dev_only_usage-transitive/ADDITION+ABANDONED": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "warning-dev_only_usage-transitive/ADDITION+ABANDONED",
			Abandoned:          true,
			Version:            contract.PkgVersion{Raw: "1.18.4", Label: "1.18.4", Semver: &contract.Semver{Major: 1, Minor: 18, Patch: 4, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            true,
			RootRequirement:    false,
			RootDevRequirement: false,
		},
		Operation: difftesting.AdditionOp,
	},
	"warning-dev_only_usage-transitive/ADDITION_NOT_SEMVER": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "warning-dev_only_usage-transitive/ADDITION_NOT_SEMVER",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "abcdefghijk", Label: "dev-master#abcdefgh", Semver: nil},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            true,
			RootRequirement:    false,
			RootDevRequirement: false,
		},
		Operation: difftesting.AdditionOp,
	},
	"warning-dev_only_usage-transitive/SEMVER_MAJOR_DOWNGRADE": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "warning-dev_only_usage-transitive/SEMVER_MAJOR_DOWNGRADE",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "1.2.0", Label: "1.2.0", Semver: &contract.Semver{Major: 1, Minor: 2, Patch: 0, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            true,
			RootRequirement:    false,
			RootDevRequirement: false,
		},
		Operation:       difftesting.DowngradeMajorOp,
		PreviousVersion: contract.PkgVersion{Raw: "2.9.2", Label: "2.9.2", Semver: &contract.Semver{Major: 2, Minor: 9, Patch: 2, Extra: ""}},
	},
	"warning-dev_only_usage-transitive/UNKNOWN_UPDATE": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "warning-dev_only_usage-transitive/UNKNOWN_UPDATE",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "12345678", Label: "2.9.x-dev#1234567", Semver: nil},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            true,
			RootRequirement:    false,
			RootDevRequirement: false,
		},
		Operation:       difftesting.UnknownUpdateOp,
		PreviousVersion: contract.PkgVersion{Raw: "2acf168", Label: "2.9.x-dev#2acf168", Semver: nil},
	},
	"warning-dev_only_usage-transitive/UNKNOWN_UPDATE+SEMVER_EXTRA": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "warning-dev_only_usage-transitive/UNKNOWN_UPDATE+SEMVER_EXTRA",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "2.9.2+alpha", Label: "2.9.2+alpha", Semver: &contract.Semver{Major: 2, Minor: 9, Patch: 2, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            true,
			RootRequirement:    false,
			RootDevRequirement: false,
		},
		Operation:       difftesting.SemverExtraUpdateOp,
		PreviousVersion: contract.PkgVersion{Raw: "2.9.2+beta", Label: "2.9.2+beta", Semver: &contract.Semver{Major: 2, Minor: 9, Patch: 2, Extra: "+beta"}},
	},
	"warning-prod_usage-requirement+dev_req/SEMVER_MAJOR_UPGRADE": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "warning-prod_usage-requirement+dev_req/SEMVER_MAJOR_UPGRADE",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "3.0.0", Label: "3.0.0", Semver: &contract.Semver{Major: 3, Minor: 0, Patch: 0, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            false,
			RootRequirement:    false,
			RootDevRequirement: true,
		},
		Operation:       difftesting.UpgradeMajorOp,
		PreviousVersion: contract.PkgVersion{Raw: "2.9.3", Label: "2.9.3", Semver: &contract.Semver{Major: 2, Minor: 9, Patch: 3, Extra: ""}},
	},
	"warning-prod_usage-requirement+dev_req/SEMVER_MINOR_DOWNGRADE": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "warning-prod_usage-requirement+dev_req/SEMVER_MINOR_DOWNGRADE",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "3.0.0", Label: "3.0.0", Semver: &contract.Semver{Major: 3, Minor: 0, Patch: 0, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            false,
			RootRequirement:    false,
			RootDevRequirement: true,
		},
		Operation:       difftesting.DowngradeMinorOp,
		PreviousVersion: contract.PkgVersion{Raw: "3.1.0", Label: "3.1.0", Semver: &contract.Semver{Major: 3, Minor: 1, Patch: 0, Extra: ""}},
	},
	"warning-prod_usage-requirement/SEMVER_MAJOR_UPGRADE": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "warning-prod_usage-requirement/SEMVER_MAJOR_UPGRADE",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "3.0.0", Label: "3.0.0", Semver: &contract.Semver{Major: 3, Minor: 0, Patch: 0, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            false,
			RootRequirement:    true,
			RootDevRequirement: false,
		},
		Operation:       difftesting.UpgradeMajorOp,
		PreviousVersion: contract.PkgVersion{Raw: "2.9.3", Label: "2.9.3", Semver: &contract.Semver{Major: 2, Minor: 9, Patch: 3, Extra: ""}},
	},
	"warning-prod_usage-requirement/SEMVER_MINOR_DOWNGRADE": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "warning-prod_usage-requirement/SEMVER_MINOR_DOWNGRADE",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "3.0.0", Label: "3.0.0", Semver: &contract.Semver{Major: 3, Minor: 0, Patch: 0, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            false,
			RootRequirement:    true,
			RootDevRequirement: false,
		},
		Operation:       difftesting.DowngradeMinorOp,
		PreviousVersion: contract.PkgVersion{Raw: "3.1.0", Label: "3.1.0", Semver: &contract.Semver{Major: 3, Minor: 1, Patch: 0, Extra: ""}},
	},
	"warning-prod_usage-requirement/ADDITION_NOT_SEMVER": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "warning-prod_usage-requirement/ADDITION_NOT_SEMVER",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "abcdefghijk", Label: "dev-master#abcdefgh", Semver: nil},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            false,
			RootRequirement:    true,
			RootDevRequirement: false,
		},
		Operation:       difftesting.AdditionOp,
		PreviousVersion: contract.PkgVersion{Raw: "2.9.3", Label: "2.9.3", Semver: &contract.Semver{Major: 2, Minor: 9, Patch: 3, Extra: ""}},
	},
	"warning-prod_usage-requirement+dev_req/ADDITION_NOT_SEMVER": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "warning-prod_usage-requirement+dev_req/ADDITION_NOT_SEMVER",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "abcdefghijk", Label: "dev-master#abcdefgh", Semver: nil},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            false,
			RootRequirement:    false,
			RootDevRequirement: true,
		},
		Operation:       difftesting.AdditionOp,
		PreviousVersion: contract.PkgVersion{Raw: "2.9.3", Label: "2.9.3", Semver: &contract.Semver{Major: 2, Minor: 9, Patch: 3, Extra: ""}},
	},
	"warning-prod_usage-transitive/ADDITION+ABANDONED": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "warning-prod_usage-transitive/ADDITION+ABANDONED",
			Abandoned:          true,
			Version:            contract.PkgVersion{Raw: "1.18.4", Label: "1.18.4", Semver: &contract.Semver{Major: 1, Minor: 18, Patch: 4, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            false,
			RootRequirement:    false,
			RootDevRequirement: false,
		},
		Operation: difftesting.AdditionOp,
	},
	"warning-prod_usage-transitive/ADDITION_NOT_SEMVER": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "warning-prod_usage-transitive/ADDITION_NOT_SEMVER",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "abcdefghijk", Label: "dev-master#abcdefgh", Semver: nil},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            false,
			RootRequirement:    false,
			RootDevRequirement: false,
		},
		Operation: difftesting.AdditionOp,
	},
	"warning-prod_usage-transitive/SEMVER_MAJOR_DOWNGRADE": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "warning-prod_usage-transitive/SEMVER_MAJOR_DOWNGRADE",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "1.2.0", Label: "1.2.0", Semver: &contract.Semver{Major: 1, Minor: 2, Patch: 0, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            false,
			RootRequirement:    false,
			RootDevRequirement: false,
		},
		Operation:       difftesting.DowngradeMajorOp,
		PreviousVersion: contract.PkgVersion{Raw: "2.9.2", Label: "2.9.2", Semver: &contract.Semver{Major: 2, Minor: 9, Patch: 2, Extra: ""}},
	},
	"warning-prod_usage-transitive/UNKNOWN_UPDATE": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "warning-prod_usage-transitive/UNKNOWN_UPDATE",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "12345678", Label: "2.9.x-dev#1234567", Semver: nil},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            false,
			RootRequirement:    false,
			RootDevRequirement: false,
		},
		Operation:       difftesting.UnknownUpdateOp,
		PreviousVersion: contract.PkgVersion{Raw: "2acf168", Label: "2.9.x-dev#2acf168", Semver: nil},
	},
	"warning-prod_usage-transitive/UNKNOWN_UPDATE+SEMVER_EXTRA": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "warning-prod_usage-transitive/UNKNOWN_UPDATE+SEMVER_EXTRA",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "2.9.2+alpha", Label: "2.9.2+alpha", Semver: &contract.Semver{Major: 2, Minor: 9, Patch: 2, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            false,
			RootRequirement:    false,
			RootDevRequirement: false,
		},
		Operation:       difftesting.SemverExtraUpdateOp,
		PreviousVersion: contract.PkgVersion{Raw: "2.9.2+beta", Label: "2.9.2+beta", Semver: &contract.Semver{Major: 2, Minor: 9, Patch: 2, Extra: "+beta"}},
	},
	"important-dev_only_usage-requirement/REMOVAL": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "important-dev_only_usage-requirement/REMOVAL",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "3.0.1", Label: "3.0.1", Semver: &contract.Semver{Major: 3, Minor: 0, Patch: 1, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            true,
			RootRequirement:    false,
			RootDevRequirement: true,
		},
		Operation: difftesting.RemovalOp,
	},
	"important-dev_only_usage-requirement/REMOVAL+ABANDONED": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "important-dev_only_usage-requirement/REMOVAL+ABANDONED",
			Abandoned:          true,
			Version:            contract.PkgVersion{Raw: "3.2.1", Label: "3.2.1", Semver: &contract.Semver{Major: 3, Minor: 2, Patch: 1, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            true,
			RootRequirement:    false,
			RootDevRequirement: true,
		},
		Operation: difftesting.RemovalOp,
	},
	"important-dev_only_usage-requirement/SEMVER_PATCH_DOWNGRADE": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "important-dev_only_usage-requirement/SEMVER_PATCH_DOWNGRADE",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "3.0.0", Label: "3.0.0", Semver: &contract.Semver{Major: 3, Minor: 0, Patch: 0, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            true,
			RootRequirement:    false,
			RootDevRequirement: true,
		},
		Operation:       difftesting.DowngradePatchOp,
		PreviousVersion: contract.PkgVersion{Raw: "3.0.1", Label: "3.0.1", Semver: &contract.Semver{Major: 3, Minor: 0, Patch: 1, Extra: ""}},
	},
	"important-dev_only_usage-requirement/SAME_NOT_SEMVER": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "important-dev_only_usage-requirement/SAME_NOT_SEMVER",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "abcdefghijk", Label: "dev-master#abcdefgh", Semver: nil},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            true,
			RootRequirement:    false,
			RootDevRequirement: true,
		},
		Operation: difftesting.SameOp,
	},
	"important-dev_only_usage-transitive/SEMVER_MAJOR_UPGRADE": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "important-dev_only_usage-transitive/SEMVER_MAJOR_UPGRADE",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "3.0.0", Label: "3.0.0", Semver: &contract.Semver{Major: 3, Minor: 0, Patch: 0, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            true,
			RootRequirement:    false,
			RootDevRequirement: false,
		},
		Operation:       difftesting.UpgradeMajorOp,
		PreviousVersion: contract.PkgVersion{Raw: "2.9.3", Label: "2.9.3", Semver: &contract.Semver{Major: 2, Minor: 9, Patch: 3, Extra: ""}},
	},
	"important-dev_only_usage-transitive/SEMVER_MINOR_DOWNGRADE": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "important-dev_only_usage-transitive/SEMVER_MINOR_DOWNGRADE",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "3.0.0", Label: "3.0.0", Semver: &contract.Semver{Major: 3, Minor: 0, Patch: 0, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            true,
			RootRequirement:    false,
			RootDevRequirement: false,
		},
		Operation:       difftesting.DowngradeMinorOp,
		PreviousVersion: contract.PkgVersion{Raw: "3.1.0", Label: "3.1.0", Semver: &contract.Semver{Major: 3, Minor: 1, Patch: 0, Extra: ""}},
	},
	"important-prod_usage-requirement+dev_req/REMOVAL": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "important-prod_usage-requirement+dev_req/REMOVAL",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "3.2.1", Label: "3.2.1", Semver: &contract.Semver{Major: 3, Minor: 2, Patch: 1, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            false,
			RootRequirement:    false,
			RootDevRequirement: true,
		},
		Operation: difftesting.RemovalOp,
	},
	"important-prod_usage-requirement+dev_req/REMOVAL+ABANDONED": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "important-prod_usage-requirement+dev_req/REMOVAL+ABANDONED",
			Abandoned:          true,
			Version:            contract.PkgVersion{Raw: "3.2.1", Label: "3.2.1", Semver: &contract.Semver{Major: 3, Minor: 2, Patch: 1, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            false,
			RootRequirement:    false,
			RootDevRequirement: true,
		},
		Operation: difftesting.RemovalOp,
	},
	"important-prod_usage-requirement+dev_req/SEMVER_PATCH_DOWNGRADE": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "important-prod_usage-requirement+dev_req/SEMVER_PATCH_DOWNGRADE",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "3.0.0", Label: "3.0.0", Semver: &contract.Semver{Major: 3, Minor: 0, Patch: 0, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            false,
			RootRequirement:    false,
			RootDevRequirement: true,
		},
		Operation:       difftesting.DowngradePatchOp,
		PreviousVersion: contract.PkgVersion{Raw: "3.0.1", Label: "3.0.1", Semver: &contract.Semver{Major: 3, Minor: 0, Patch: 1, Extra: ""}},
	},
	"important-prod_usage-requirement/REMOVAL": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "important-prod_usage-requirement/REMOVAL",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "3.0.1", Label: "3.0.1", Semver: &contract.Semver{Major: 3, Minor: 0, Patch: 1, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            false,
			RootRequirement:    true,
			RootDevRequirement: false,
		},
		Operation: difftesting.RemovalOp,
	},
	"important-prod_usage-requirement/REMOVAL+ABANDONED": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "important-prod_usage-requirement/REMOVAL+ABANDONED",
			Abandoned:          true,
			Version:            contract.PkgVersion{Raw: "3.2.1", Label: "3.2.1", Semver: &contract.Semver{Major: 3, Minor: 2, Patch: 1, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            false,
			RootRequirement:    true,
			RootDevRequirement: false,
		},
		Operation: difftesting.RemovalOp,
	},
	"important-prod_usage-requirement/SEMVER_PATCH_DOWNGRADE": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "important-prod_usage-requirement/SEMVER_PATCH_DOWNGRADE",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "3.0.0", Label: "3.0.0", Semver: &contract.Semver{Major: 3, Minor: 0, Patch: 0, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            false,
			RootRequirement:    true,
			RootDevRequirement: false,
		},
		Operation:       difftesting.DowngradePatchOp,
		PreviousVersion: contract.PkgVersion{Raw: "3.0.1", Label: "3.0.1", Semver: &contract.Semver{Major: 3, Minor: 0, Patch: 1, Extra: ""}},
	},
	"important-prod_usage-requirement/SAME_NOT_SEMVER": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "important-prod_usage-requirement/SAME_NOT_SEMVER",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "abcdefghijk", Label: "dev-master#abcdefgh", Semver: nil},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            false,
			RootRequirement:    false,
			RootDevRequirement: true,
		},
		Operation: difftesting.SameOp,
	},
	"important-prod_usage-requirement+dev_req/SAME_NOT_SEMVER": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "important-prod_usage-requirement+dev_req/SAME_NOT_SEMVER",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "abcdefghijk", Label: "dev-master#abcdefgh", Semver: nil},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            false,
			RootRequirement:    true,
			RootDevRequirement: false,
		},
		Operation: difftesting.SameOp,
	},
	"important-prod_usage-transitive/SEMVER_MAJOR_UPGRADE": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "important-prod_usage-transitive/SEMVER_MAJOR_UPGRADE",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "3.0.0", Label: "3.0.0", Semver: &contract.Semver{Major: 3, Minor: 0, Patch: 0, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            false,
			RootRequirement:    false,
			RootDevRequirement: false,
		},
		Operation:       difftesting.UpgradeMajorOp,
		PreviousVersion: contract.PkgVersion{Raw: "2.9.3", Label: "2.9.3", Semver: &contract.Semver{Major: 2, Minor: 9, Patch: 3, Extra: ""}},
	},
	"important-prod_usage-transitive/SEMVER_MINOR_DOWNGRADE": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "important-prod_usage-transitive/SEMVER_MINOR_DOWNGRADE",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "3.0.0", Label: "3.0.0", Semver: &contract.Semver{Major: 3, Minor: 0, Patch: 0, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            false,
			RootRequirement:    false,
			RootDevRequirement: false,
		},
		Operation:       difftesting.DowngradeMinorOp,
		PreviousVersion: contract.PkgVersion{Raw: "3.1.0", Label: "3.1.0", Semver: &contract.Semver{Major: 3, Minor: 1, Patch: 0, Extra: ""}},
	},
	"tip-dev_only_usage-requirement/ADDITION": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "tip-dev_only_usage-requirement/ADDITION",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "3.0.1", Label: "3.0.1", Semver: &contract.Semver{Major: 3, Minor: 0, Patch: 1, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            true,
			RootRequirement:    false,
			RootDevRequirement: true,
		},
		Operation: difftesting.AdditionOp,
	},
	"tip-dev_only_usage-requirement/SEMVER_MINOR_UPGRADE": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "tip-dev_only_usage-requirement/SEMVER_MINOR_UPGRADE",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "3.1.0", Label: "3.1.0", Semver: &contract.Semver{Major: 3, Minor: 1, Patch: 0, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            true,
			RootRequirement:    false,
			RootDevRequirement: true,
		},
		Operation:       difftesting.UpgradeMinorOp,
		PreviousVersion: contract.PkgVersion{Raw: "3.0.0", Label: "3.0.0", Semver: &contract.Semver{Major: 3, Minor: 0, Patch: 0, Extra: ""}},
	},
	"tip-dev_only_usage-requirement/SEMVER_MINOR_UPGRADE+ABANDONED": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "tip-dev_only_usage-requirement/SEMVER_MINOR_UPGRADE+ABANDONED",
			Abandoned:          true,
			Version:            contract.PkgVersion{Raw: "3.2.0", Label: "3.2.0", Semver: &contract.Semver{Major: 3, Minor: 2, Patch: 0, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            true,
			RootRequirement:    false,
			RootDevRequirement: true,
		},
		Operation:       difftesting.UpgradeMinorOp,
		PreviousVersion: contract.PkgVersion{Raw: "3.0.1", Label: "3.0.1", Semver: &contract.Semver{Major: 3, Minor: 0, Patch: 1, Extra: ""}},
	},
	"tip-dev_only_usage-transitive/REMOVAL": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "tip-dev_only_usage-transitive/REMOVAL",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "3.0.1", Label: "3.0.1", Semver: &contract.Semver{Major: 3, Minor: 0, Patch: 1, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            true,
			RootRequirement:    false,
			RootDevRequirement: false,
		},
		Operation: difftesting.RemovalOp,
	},
	"tip-dev_only_usage-transitive/REMOVAL+ABANDONED": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "tip-dev_only_usage-transitive/REMOVAL+ABANDONED",
			Abandoned:          true,
			Version:            contract.PkgVersion{Raw: "3.2.1", Label: "3.2.1", Semver: &contract.Semver{Major: 3, Minor: 2, Patch: 1, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            true,
			RootRequirement:    false,
			RootDevRequirement: false,
		},
		Operation: difftesting.RemovalOp,
	},
	"tip-dev_only_usage-transitive/SEMVER_PATCH_DOWNGRADE": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "tip-dev_only_usage-transitive/SEMVER_PATCH_DOWNGRADE",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "3.0.0", Label: "3.0.0", Semver: &contract.Semver{Major: 3, Minor: 0, Patch: 0, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            true,
			RootRequirement:    false,
			RootDevRequirement: false,
		},
		Operation:       difftesting.DowngradePatchOp,
		PreviousVersion: contract.PkgVersion{Raw: "3.0.1", Label: "3.0.1", Semver: &contract.Semver{Major: 3, Minor: 0, Patch: 1, Extra: ""}},
	},
	"tip-dev_only_usage-transitive/SAME_NOT_SEMVER": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "tip-dev_only_usage-transitive/SAME_NOT_SEMVER",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "abcdefghijk", Label: "dev-master#abcdefgh", Semver: nil},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            true,
			RootRequirement:    false,
			RootDevRequirement: false,
		},
		Operation: difftesting.SameOp,
	},
	"tip-prod_usage-requirement+dev_req/ADDITION": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "tip-prod_usage-requirement+dev_req/ADDITION",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "1.18.4", Label: "1.18.4", Semver: &contract.Semver{Major: 1, Minor: 18, Patch: 4, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            false,
			RootRequirement:    false,
			RootDevRequirement: true,
		},
		Operation: difftesting.AdditionOp,
	},
	"tip-prod_usage-requirement+dev_req/SEMVER_MINOR_UPGRADE": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "tip-prod_usage-requirement+dev_req/SEMVER_MINOR_UPGRADE",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "3.1.0", Label: "3.1.0", Semver: &contract.Semver{Major: 3, Minor: 1, Patch: 0, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            false,
			RootRequirement:    false,
			RootDevRequirement: true,
		},
		Operation:       difftesting.UpgradeMinorOp,
		PreviousVersion: contract.PkgVersion{Raw: "3.0.0", Label: "3.0.0", Semver: &contract.Semver{Major: 3, Minor: 0, Patch: 0, Extra: ""}},
	},
	"tip-prod_usage-requirement+dev_req/SEMVER_MINOR_UPGRADE+ABANDONED": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "tip-prod_usage-requirement+dev_req/SEMVER_MINOR_UPGRADE+ABANDONED",
			Abandoned:          true,
			Version:            contract.PkgVersion{Raw: "3.2.0", Label: "3.2.0", Semver: &contract.Semver{Major: 3, Minor: 2, Patch: 0, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            false,
			RootRequirement:    false,
			RootDevRequirement: true,
		},
		Operation:       difftesting.UpgradeMinorOp,
		PreviousVersion: contract.PkgVersion{Raw: "3.0.1", Label: "3.0.1", Semver: &contract.Semver{Major: 3, Minor: 0, Patch: 1, Extra: ""}},
	},
	"tip-prod_usage-requirement/ADDITION": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "tip-prod_usage-requirement/ADDITION",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "1.18.4", Label: "1.18.4", Semver: &contract.Semver{Major: 1, Minor: 18, Patch: 4, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            false,
			RootRequirement:    true,
			RootDevRequirement: false,
		},
		Operation: difftesting.AdditionOp,
	},
	"tip-prod_usage-requirement/SEMVER_MINOR_UPGRADE": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "tip-prod_usage-requirement/SEMVER_MINOR_UPGRADE",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "3.1.0", Label: "3.1.0", Semver: &contract.Semver{Major: 3, Minor: 1, Patch: 0, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            false,
			RootRequirement:    true,
			RootDevRequirement: false,
		},
		Operation:       difftesting.UpgradeMinorOp,
		PreviousVersion: contract.PkgVersion{Raw: "3.0.0", Label: "3.0.0", Semver: &contract.Semver{Major: 3, Minor: 0, Patch: 0, Extra: ""}},
	},
	"tip-prod_usage-requirement/SEMVER_MINOR_UPGRADE+ABANDONED": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "tip-prod_usage-requirement/SEMVER_MINOR_UPGRADE+ABANDONED",
			Abandoned:          true,
			Version:            contract.PkgVersion{Raw: "3.2.0", Label: "3.2.0", Semver: &contract.Semver{Major: 3, Minor: 2, Patch: 0, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            false,
			RootRequirement:    true,
			RootDevRequirement: false,
		},
		Operation:       difftesting.UpgradeMinorOp,
		PreviousVersion: contract.PkgVersion{Raw: "3.0.1", Label: "3.0.1", Semver: &contract.Semver{Major: 3, Minor: 0, Patch: 1, Extra: ""}},
	},
	"tip-prod_usage-transitive/REMOVAL": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "tip-prod_usage-transitive/REMOVAL",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "3.0.1", Label: "3.0.1", Semver: &contract.Semver{Major: 3, Minor: 0, Patch: 1, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            false,
			RootRequirement:    false,
			RootDevRequirement: false,
		},
		Operation: difftesting.RemovalOp,
	},
	"tip-prod_usage-transitive/REMOVAL+ABANDONED": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "tip-prod_usage-transitive/REMOVAL+ABANDONED",
			Abandoned:          true,
			Version:            contract.PkgVersion{Raw: "3.2.1", Label: "3.2.1", Semver: &contract.Semver{Major: 3, Minor: 2, Patch: 1, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            false,
			RootRequirement:    false,
			RootDevRequirement: false,
		},
		Operation: difftesting.RemovalOp,
	},
	"tip-prod_usage-transitive/SEMVER_PATCH_DOWNGRADE": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "tip-prod_usage-transitive/SEMVER_PATCH_DOWNGRADE",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "3.0.0", Label: "3.0.0", Semver: &contract.Semver{Major: 3, Minor: 0, Patch: 0, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            false,
			RootRequirement:    false,
			RootDevRequirement: false,
		},
		Operation:       difftesting.DowngradePatchOp,
		PreviousVersion: contract.PkgVersion{Raw: "3.0.1", Label: "3.0.1", Semver: &contract.Semver{Major: 3, Minor: 0, Patch: 1, Extra: ""}},
	},
	"tip-prod_usage-transitive/SAME_NOT_SEMVER": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "tip-prod_usage-transitive/SAME_NOT_SEMVER",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "abcdefghijk", Label: "dev-master#abcdefgh", Semver: nil},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            false,
			RootRequirement:    false,
			RootDevRequirement: false,
		},
		Operation:       difftesting.SameOp,
		PreviousVersion: contract.PkgVersion{Raw: "3.1.0", Label: "3.1.0", Semver: &contract.Semver{Major: 3, Minor: 1, Patch: 0, Extra: ""}},
	},
	"note-dev_only_usage-requirement/SAME": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "note-dev_only_usage-requirement/SAME",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "3.1.1", Label: "3.1.1", Semver: &contract.Semver{Major: 3, Minor: 1, Patch: 1, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            true,
			RootRequirement:    false,
			RootDevRequirement: true,
		},
		Operation: difftesting.SameOp,
	},
	"note-dev_only_usage-requirement/SAME+ABANDONED": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "note-dev_only_usage-requirement/SAME+ABANDONED",
			Abandoned:          true,
			Version:            contract.PkgVersion{Raw: "3.1.1", Label: "3.1.1", Semver: &contract.Semver{Major: 3, Minor: 1, Patch: 1, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            true,
			RootRequirement:    false,
			RootDevRequirement: true,
		},
		Operation: difftesting.SameOp,
	},
	"note-dev_only_usage-requirement/SEMVER_PATCH_UPGRADE": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "note-dev_only_usage-requirement/SEMVER_PATCH_UPGRADE",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "3.0.1", Label: "3.0.1", Semver: &contract.Semver{Major: 3, Minor: 0, Patch: 1, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            true,
			RootRequirement:    false,
			RootDevRequirement: true,
		},
		Operation:       difftesting.UpgradePatchOp,
		PreviousVersion: contract.PkgVersion{Raw: "3.0.0", Label: "3.0.0", Semver: &contract.Semver{Major: 3, Minor: 0, Patch: 0, Extra: ""}},
	},
	"note-dev_only_usage-transitive/ADDITION": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "note-dev_only_usage-transitive/ADDITION",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "1.18.4", Label: "1.18.4", Semver: &contract.Semver{Major: 1, Minor: 18, Patch: 4, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            true,
			RootRequirement:    false,
			RootDevRequirement: false,
		},
		Operation: difftesting.AdditionOp,
	},
	"note-dev_only_usage-transitive/SAME": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "note-dev_only_usage-transitive/SAME",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "3.1.1", Label: "3.1.1", Semver: &contract.Semver{Major: 3, Minor: 1, Patch: 1, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            true,
			RootRequirement:    false,
			RootDevRequirement: false,
		},
		Operation: difftesting.SameOp,
	},
	"note-dev_only_usage-transitive/SAME+ABANDONED": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "note-dev_only_usage-transitive/SAME+ABANDONED",
			Abandoned:          true,
			Version:            contract.PkgVersion{Raw: "3.1.1", Label: "3.1.1", Semver: &contract.Semver{Major: 3, Minor: 1, Patch: 1, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            true,
			RootRequirement:    false,
			RootDevRequirement: false,
		},
		Operation: difftesting.SameOp,
	},
	"note-dev_only_usage-transitive/SEMVER_MINOR_UPGRADE": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "note-dev_only_usage-transitive/SEMVER_MINOR_UPGRADE",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "3.1.0", Label: "3.1.0", Semver: &contract.Semver{Major: 3, Minor: 1, Patch: 0, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            true,
			RootRequirement:    false,
			RootDevRequirement: false,
		},
		Operation:       difftesting.UpgradeMinorOp,
		PreviousVersion: contract.PkgVersion{Raw: "3.0.0", Label: "3.0.0", Semver: &contract.Semver{Major: 3, Minor: 0, Patch: 0, Extra: ""}},
	},
	"note-dev_only_usage-transitive/SEMVER_MINOR_UPGRADE+ABANDONED": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "note-dev_only_usage-transitive/SEMVER_MINOR_UPGRADE+ABANDONED",
			Abandoned:          true,
			Version:            contract.PkgVersion{Raw: "3.2.0", Label: "3.2.0", Semver: &contract.Semver{Major: 3, Minor: 2, Patch: 0, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            true,
			RootRequirement:    false,
			RootDevRequirement: false,
		},
		Operation:       difftesting.UpgradeMinorOp,
		PreviousVersion: contract.PkgVersion{Raw: "3.0.1", Label: "3.0.1", Semver: &contract.Semver{Major: 3, Minor: 0, Patch: 1, Extra: ""}},
	},
	"note-dev_only_usage-transitive/SEMVER_PATCH_UPGRADE": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "note-dev_only_usage-transitive/SEMVER_PATCH_UPGRADE",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "3.1.1", Label: "3.1.1", Semver: &contract.Semver{Major: 3, Minor: 1, Patch: 1, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            true,
			RootRequirement:    false,
			RootDevRequirement: false,
		},
		Operation:       difftesting.UpgradePatchOp,
		PreviousVersion: contract.PkgVersion{Raw: "3.1.0", Label: "3.1.0", Semver: &contract.Semver{Major: 3, Minor: 1, Patch: 0, Extra: ""}},
	},
	"note-prod_usage-requirement+dev_req/SAME": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "note-prod_usage-requirement+dev_req/SAME",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "3.1.1", Label: "3.1.1", Semver: &contract.Semver{Major: 3, Minor: 1, Patch: 1, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            false,
			RootRequirement:    false,
			RootDevRequirement: true,
		},
		Operation: difftesting.SameOp,
	},
	"note-prod_usage-requirement+dev_req/SAME+ABANDONED": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "note-prod_usage-requirement+dev_req/SAME+ABANDONED",
			Abandoned:          true,
			Version:            contract.PkgVersion{Raw: "3.1.1", Label: "3.1.1", Semver: &contract.Semver{Major: 3, Minor: 1, Patch: 1, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            false,
			RootRequirement:    false,
			RootDevRequirement: true,
		},
		Operation: difftesting.SameOp,
	},
	"note-prod_usage-requirement+dev_req/SEMVER_PATCH_UPGRADE": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "note-prod_usage-requirement+dev_req/SEMVER_PATCH_UPGRADE",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "3.1.1", Label: "3.1.1", Semver: &contract.Semver{Major: 3, Minor: 1, Patch: 1, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            false,
			RootRequirement:    false,
			RootDevRequirement: true,
		},
		Operation:       difftesting.UpgradePatchOp,
		PreviousVersion: contract.PkgVersion{Raw: "3.1.0", Label: "3.1.0", Semver: &contract.Semver{Major: 3, Minor: 1, Patch: 0, Extra: ""}},
	},
	"note-prod_usage-requirement/SAME": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "note-prod_usage-requirement/SAME",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "3.1.1", Label: "3.1.1", Semver: &contract.Semver{Major: 3, Minor: 1, Patch: 1, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            false,
			RootRequirement:    true,
			RootDevRequirement: false,
		},
		Operation: difftesting.SameOp,
	},
	"note-prod_usage-requirement/SAME+ABANDONED": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "note-prod_usage-requirement/SAME+ABANDONED",
			Abandoned:          true,
			Version:            contract.PkgVersion{Raw: "3.1.1", Label: "3.1.1", Semver: &contract.Semver{Major: 3, Minor: 1, Patch: 1, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            false,
			RootRequirement:    true,
			RootDevRequirement: false,
		},
		Operation: difftesting.SameOp,
	},
	"note-prod_usage-requirement/SEMVER_PATCH_UPGRADE": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "note-prod_usage-requirement/SEMVER_PATCH_UPGRADE",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "3.1.1", Label: "3.1.1", Semver: &contract.Semver{Major: 3, Minor: 1, Patch: 1, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            false,
			RootRequirement:    true,
			RootDevRequirement: false,
		},
		Operation:       difftesting.UpgradePatchOp,
		PreviousVersion: contract.PkgVersion{Raw: "3.1.0", Label: "3.1.0", Semver: &contract.Semver{Major: 3, Minor: 1, Patch: 0, Extra: ""}},
	},
	"note-prod_usage-transitive/ADDITION": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "note-prod_usage-transitive/ADDITION",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "1.18.4", Label: "1.18.4", Semver: &contract.Semver{Major: 1, Minor: 18, Patch: 4, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            false,
			RootRequirement:    false,
			RootDevRequirement: false,
		},
		Operation: difftesting.AdditionOp,
	},
	"note-prod_usage-transitive/SAME": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "note-prod_usage-transitive/SAME",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "3.1.1", Label: "3.1.1", Semver: &contract.Semver{Major: 3, Minor: 1, Patch: 1, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            false,
			RootRequirement:    false,
			RootDevRequirement: false,
		},
		Operation: difftesting.SameOp,
	},
	"note-prod_usage-transitive/SAME+ABANDONED": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "note-prod_usage-transitive/SAME+ABANDONED",
			Abandoned:          true,
			Version:            contract.PkgVersion{Raw: "3.1.1", Label: "3.1.1", Semver: &contract.Semver{Major: 3, Minor: 1, Patch: 1, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            false,
			RootRequirement:    false,
			RootDevRequirement: false,
		},
		Operation: difftesting.SameOp,
	},
	"note-prod_usage-transitive/SEMVER_MINOR_UPGRADE": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "note-prod_usage-transitive/SEMVER_MINOR_UPGRADE",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "3.1.0", Label: "3.1.0", Semver: &contract.Semver{Major: 3, Minor: 1, Patch: 0, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            false,
			RootRequirement:    false,
			RootDevRequirement: false,
		},
		Operation:       difftesting.UpgradeMinorOp,
		PreviousVersion: contract.PkgVersion{Raw: "3.0.0", Label: "3.0.0", Semver: &contract.Semver{Major: 3, Minor: 0, Patch: 0, Extra: ""}},
	},
	"note-prod_usage-transitive/SEMVER_MINOR_UPGRADE+ABANDONED": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "note-prod_usage-transitive/SEMVER_MINOR_UPGRADE+ABANDONED",
			Abandoned:          true,
			Version:            contract.PkgVersion{Raw: "3.2.0", Label: "3.2.0", Semver: &contract.Semver{Major: 3, Minor: 2, Patch: 0, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            false,
			RootRequirement:    false,
			RootDevRequirement: false,
		},
		Operation:       difftesting.UpgradeMinorOp,
		PreviousVersion: contract.PkgVersion{Raw: "3.0.1", Label: "3.0.1", Semver: &contract.Semver{Major: 3, Minor: 0, Patch: 1, Extra: ""}},
	},
	"note-prod_usage-transitive/SEMVER_PATCH_UPGRADE": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "note-prod_usage-transitive/SEMVER_PATCH_UPGRADE",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "3.1.1", Label: "3.1.1", Semver: &contract.Semver{Major: 3, Minor: 1, Patch: 1, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            false,
			RootRequirement:    false,
			RootDevRequirement: false,
		},
		Operation:       difftesting.UpgradePatchOp,
		PreviousVersion: contract.PkgVersion{Raw: "3.1.0", Label: "3.1.0", Semver: &contract.Semver{Major: 3, Minor: 1, Patch: 0, Extra: ""}},
	},
}

var _integrationOnlyThreeColumnsNeeded = contract.DiffMap{
	"caution-dev_only_usage-requirement/ADDITION+ABANDONED": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "caution-dev_only_usage-requirement/ADDITION+ABANDONED",
			Abandoned:          true,
			Version:            contract.PkgVersion{Raw: "1.18.4", Label: "1.18.4", Semver: &contract.Semver{Major: 1, Minor: 18, Patch: 4, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            true,
			RootRequirement:    false,
			RootDevRequirement: true,
		},
		Operation: difftesting.AdditionOp,
	},
	"caution-prod_usage-requirement+dev_req/ADDITION+ABANDONED": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "caution-prod_usage-requirement+dev_req/ADDITION+ABANDONED",
			Abandoned:          true,
			Version:            contract.PkgVersion{Raw: "1.18.4", Label: "1.18.4", Semver: &contract.Semver{Major: 1, Minor: 18, Patch: 4, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            false,
			RootRequirement:    false,
			RootDevRequirement: true,
		},
		Operation: difftesting.AdditionOp,
	},
	"caution-prod_usage-requirement/ADDITION+ABANDONED": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "caution-prod_usage-requirement/ADDITION+ABANDONED",
			Abandoned:          true,
			Version:            contract.PkgVersion{Raw: "1.18.4", Label: "1.18.4", Semver: &contract.Semver{Major: 1, Minor: 18, Patch: 4, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            false,
			RootRequirement:    true,
			RootDevRequirement: false,
		},
		Operation: difftesting.AdditionOp,
	},
	"warning-dev_only_usage-transitive/ADDITION+ABANDONED": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "warning-dev_only_usage-transitive/ADDITION+ABANDONED",
			Abandoned:          true,
			Version:            contract.PkgVersion{Raw: "1.18.4", Label: "1.18.4", Semver: &contract.Semver{Major: 1, Minor: 18, Patch: 4, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            true,
			RootRequirement:    false,
			RootDevRequirement: false,
		},
		Operation: difftesting.AdditionOp,
	},
	"warning-prod_usage-transitive/ADDITION+ABANDONED": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "warning-prod_usage-transitive/ADDITION+ABANDONED",
			Abandoned:          true,
			Version:            contract.PkgVersion{Raw: "1.18.4", Label: "1.18.4", Semver: &contract.Semver{Major: 1, Minor: 18, Patch: 4, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            false,
			RootRequirement:    false,
			RootDevRequirement: false,
		},
		Operation: difftesting.AdditionOp,
	},
	"important-dev_only_usage-requirement/REMOVAL": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "important-dev_only_usage-requirement/REMOVAL",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "3.0.1", Label: "3.0.1", Semver: &contract.Semver{Major: 3, Minor: 0, Patch: 1, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            true,
			RootRequirement:    false,
			RootDevRequirement: true,
		},
		Operation: difftesting.RemovalOp,
	},
	"important-dev_only_usage-requirement/REMOVAL+ABANDONED": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "important-dev_only_usage-requirement/REMOVAL+ABANDONED",
			Abandoned:          true,
			Version:            contract.PkgVersion{Raw: "3.2.1", Label: "3.2.1", Semver: &contract.Semver{Major: 3, Minor: 2, Patch: 1, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            true,
			RootRequirement:    false,
			RootDevRequirement: true,
		},
		Operation: difftesting.RemovalOp,
	},
	"important-prod_usage-requirement+dev_req/REMOVAL": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "important-prod_usage-requirement+dev_req/REMOVAL",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "3.2.1", Label: "3.2.1", Semver: &contract.Semver{Major: 3, Minor: 2, Patch: 1, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            false,
			RootRequirement:    false,
			RootDevRequirement: true,
		},
		Operation: difftesting.RemovalOp,
	},
	"important-prod_usage-requirement+dev_req/REMOVAL+ABANDONED": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "important-prod_usage-requirement+dev_req/REMOVAL+ABANDONED",
			Abandoned:          true,
			Version:            contract.PkgVersion{Raw: "3.2.1", Label: "3.2.1", Semver: &contract.Semver{Major: 3, Minor: 2, Patch: 1, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            false,
			RootRequirement:    false,
			RootDevRequirement: true,
		},
		Operation: difftesting.RemovalOp,
	},
	"important-prod_usage-requirement/REMOVAL": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "important-prod_usage-requirement/REMOVAL",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "3.0.1", Label: "3.0.1", Semver: &contract.Semver{Major: 3, Minor: 0, Patch: 1, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            false,
			RootRequirement:    true,
			RootDevRequirement: false,
		},
		Operation: difftesting.RemovalOp,
	},
	"important-prod_usage-requirement/REMOVAL+ABANDONED": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "important-prod_usage-requirement/REMOVAL+ABANDONED",
			Abandoned:          true,
			Version:            contract.PkgVersion{Raw: "3.2.1", Label: "3.2.1", Semver: &contract.Semver{Major: 3, Minor: 2, Patch: 1, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            false,
			RootRequirement:    true,
			RootDevRequirement: false,
		},
		Operation: difftesting.RemovalOp,
	},
	"tip-dev_only_usage-requirement/ADDITION": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "tip-dev_only_usage-requirement/ADDITION",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "3.0.1", Label: "3.0.1", Semver: &contract.Semver{Major: 3, Minor: 0, Patch: 1, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            true,
			RootRequirement:    false,
			RootDevRequirement: true,
		},
		Operation: difftesting.AdditionOp,
	},
	"tip-dev_only_usage-transitive/REMOVAL": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "tip-dev_only_usage-transitive/REMOVAL",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "3.0.1", Label: "3.0.1", Semver: &contract.Semver{Major: 3, Minor: 0, Patch: 1, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            true,
			RootRequirement:    false,
			RootDevRequirement: false,
		},
		Operation: difftesting.RemovalOp,
	},
	"tip-dev_only_usage-transitive/REMOVAL+ABANDONED": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "tip-dev_only_usage-transitive/REMOVAL+ABANDONED",
			Abandoned:          true,
			Version:            contract.PkgVersion{Raw: "3.2.1", Label: "3.2.1", Semver: &contract.Semver{Major: 3, Minor: 2, Patch: 1, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            true,
			RootRequirement:    false,
			RootDevRequirement: false,
		},
		Operation: difftesting.RemovalOp,
	},
	"tip-prod_usage-requirement+dev_req/ADDITION": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "tip-prod_usage-requirement+dev_req/ADDITION",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "1.18.4", Label: "1.18.4", Semver: &contract.Semver{Major: 1, Minor: 18, Patch: 4, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            false,
			RootRequirement:    false,
			RootDevRequirement: true,
		},
		Operation: difftesting.AdditionOp,
	},
	"tip-prod_usage-requirement/ADDITION": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "tip-prod_usage-requirement/ADDITION",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "1.18.4", Label: "1.18.4", Semver: &contract.Semver{Major: 1, Minor: 18, Patch: 4, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            false,
			RootRequirement:    true,
			RootDevRequirement: false,
		},
		Operation: difftesting.AdditionOp,
	},
	"tip-prod_usage-transitive/REMOVAL": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "tip-prod_usage-transitive/REMOVAL",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "3.0.1", Label: "3.0.1", Semver: &contract.Semver{Major: 3, Minor: 0, Patch: 1, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            false,
			RootRequirement:    false,
			RootDevRequirement: false,
		},
		Operation: difftesting.RemovalOp,
	},
	"tip-prod_usage-transitive/REMOVAL+ABANDONED": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "tip-prod_usage-transitive/REMOVAL+ABANDONED",
			Abandoned:          true,
			Version:            contract.PkgVersion{Raw: "3.2.1", Label: "3.2.1", Semver: &contract.Semver{Major: 3, Minor: 2, Patch: 1, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            false,
			RootRequirement:    false,
			RootDevRequirement: false,
		},
		Operation: difftesting.RemovalOp,
	},
	"note-dev_only_usage-requirement/SAME": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "note-dev_only_usage-requirement/SAME",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "3.1.1", Label: "3.1.1", Semver: &contract.Semver{Major: 3, Minor: 1, Patch: 1, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            true,
			RootRequirement:    false,
			RootDevRequirement: true,
		},
		Operation: difftesting.SameOp,
	},
	"note-dev_only_usage-transitive/ADDITION": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "note-dev_only_usage-transitive/ADDITION",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "1.18.4", Label: "1.18.4", Semver: &contract.Semver{Major: 1, Minor: 18, Patch: 4, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            true,
			RootRequirement:    false,
			RootDevRequirement: false,
		},
		Operation: difftesting.AdditionOp,
	},
	"note-prod_usage-requirement/SAME": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "note-prod_usage-requirement/SAME",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "3.1.1", Label: "3.1.1", Semver: &contract.Semver{Major: 3, Minor: 1, Patch: 1, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            false,
			RootRequirement:    true,
			RootDevRequirement: false,
		},
		Operation: difftesting.SameOp,
	},
	"note-prod_usage-transitive/ADDITION": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "note-prod_usage-transitive/ADDITION",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "1.18.4", Label: "1.18.4", Semver: &contract.Semver{Major: 1, Minor: 18, Patch: 4, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            false,
			RootRequirement:    false,
			RootDevRequirement: false,
		},
		Operation: difftesting.AdditionOp,
	},
}

var _integrationForceOpenedClosed = contract.DiffMap{
	"note-dev_only_usage-requirement/SAME": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "note-dev_only_usage-requirement/SAME",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "3.1.1", Label: "3.1.1", Semver: &contract.Semver{Major: 3, Minor: 1, Patch: 1, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            true,
			RootRequirement:    false,
			RootDevRequirement: true,
		},
		Operation: difftesting.SameOp,
	},
	"note-dev_only_usage-requirement/SAME-2": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "note-dev_only_usage-requirement/SAME-2",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "3.1.1", Label: "3.1.1", Semver: &contract.Semver{Major: 3, Minor: 1, Patch: 1, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            true,
			RootRequirement:    false,
			RootDevRequirement: true,
		},
		Operation: difftesting.SameOp,
	},
	"note-dev_only_usage-requirement/SAME-3": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "note-dev_only_usage-requirement/SAME-3",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "3.1.1", Label: "3.1.1", Semver: &contract.Semver{Major: 3, Minor: 1, Patch: 1, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            true,
			RootRequirement:    false,
			RootDevRequirement: true,
		},
		Operation: difftesting.SameOp,
	},
	"note-dev_only_usage-requirement/SAME-4": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "note-dev_only_usage-requirement/SAME-4",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "3.1.1", Label: "3.1.1", Semver: &contract.Semver{Major: 3, Minor: 1, Patch: 1, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            true,
			RootRequirement:    false,
			RootDevRequirement: true,
		},
		Operation: difftesting.SameOp,
	},
	"note-prod_usage-requirement/SAME": {
		Package: &difftesting.TestPkgWrapper{
			Name:               "note-prod_usage-requirement/SAME",
			Abandoned:          false,
			Version:            contract.PkgVersion{Raw: "3.1.1", Label: "3.1.1", Semver: &contract.Semver{Major: 3, Minor: 1, Patch: 1, Extra: ""}},
			Link:               "http://www.squizlabs.com/php-codesniffer",
			DevOnly:            false,
			RootRequirement:    true,
			RootDevRequirement: false,
		},
		Operation: difftesting.SameOp,
	},
}
