package markdown

import (
	"iter"
	"strings"
)

// HTMLTable writes an HTML table with rows generated by the provided iterator.
// Each row is represented as a slice of cell strings (HTML) and is wrapped in <tr> tags.
// The table is wrapped in <table> tags and properly indented.
//
// Parameters:
//   - rowIterator: An iterator yielding []string for each row. Each element in the
//     slice is treated as pre-formatted HTML content for a table cell (should include
//     <td> tags).
//   - indentDepth: The indentation level for the <table> and <tr> tags
//
// Output Format:
// The function produces HTML like:
//
//	<table>
//	  <tr><td>A</td><td>B</td></tr>
//	  <tr><td>C</td><td>D</td></tr>
//	</table>
//
// Example:
//
//	builder.HTMLTable(func(yield func([]string) bool) {
//		yield([]string{"<td>A</td>", "<td>B</td>"})
//		yield([]string{"<td>C</td>", "<td>D</td>"})
//	}, 0)
func (c *Builder) HTMLTable(rowIterator iter.Seq[[]string], indentDepth int) {
	c.WriteLine("<table>", indentDepth)

	for cells := range rowIterator {
		c.WriteLine("<tr>"+strings.Join(cells, "")+"</tr>", indentDepth+1)
	}

	c.WriteLine("</table>", indentDepth)
	c.WriteEol()
}
