package markdown

import "strings"

// Header writes a Markdown header with the specified level and indentation.
// It creates headers using Markdown syntax (# for H1, ## for H2, etc.) and adds
// blank lines before and after for proper Markdown formatting.
//
// Parameters:
//   - header: The header text content
//   - level: Header level (1 = #, 2 = ##, 3 = ###, etc.)
//   - indentDepth: The indentation level for the header line
//
// Example:
//
//	builder.Header("Main Title", 1, 0)     // Produces: # Main Title
//	builder.Header("Section", 2, 0)        // Produces: ## Section
//	builder.Header("Subsection", 3, 1)     // Produces: (indented) ### Subsection
func (c *Builder) Header(header string, level int, indentDepth int) {
	c.WriteEol()
	c.WriteLine(strings.Repeat("#", level)+" "+header, indentDepth)
	c.WriteEol()
}

// Details writes an HTML <details> collapsible section with custom content.
// The content is generated by calling the provided contentBuilder callback function,
// which receives the builder and current indentation depth.
//
// Parameters:
//   - summary: The text displayed in the <summary> element (always visible)
//   - contentBuilder: A callback function that builds the collapsible content.
//     Receives the builder and indentation depth for nested content.
//   - opened: If true, the details section starts expanded (open attribute).
//     If false, the section starts collapsed.
//   - indentDepth: The indentation level for the <details> tags
//
// Example:
//
//	builder.Details("Click to expand", func(b *Builder, depth int) {
//		b.WriteLine("Hidden content", depth)
//	}, false, 0)
//	// Produces: <details><summary>Click to expand</summary>Hidden content</details>
func (c *Builder) Details(
	summary string,
	contentBuilder func(c *Builder, indentDepth int),
	opened bool,
	indentDepth int,
) {
	openDirective := ""
	if opened {
		openDirective = " open"
	}

	c.WriteLine("<details"+openDirective+">", indentDepth)
	c.WriteLine("<summary>"+summary+"</summary>", indentDepth+1)
	contentBuilder(c, indentDepth+1)
	c.WriteLine("</details>", indentDepth)
}
