name: Benchmark

on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches: [master]

concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  benchmark:
    name: Regression check
    if: github.event_name == 'push' || ( github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'with-benchmark') )
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: ./go.mod
          check-latest: true
          cache: true
          cache-dependency-path: ./go.sum

      - name: Install benchstat tool
        if: steps.cache.outputs.cache-hit != 'true'
        run: go install golang.org/x/perf/cmd/benchstat@latest

      - name: Run benchmarks on current code
        run: make benchmark bench_o="-count=7" | tee current.txt

      - name: PR - Checkout base branch
        if: github.event_name == 'pull_request'
        run: git checkout ${{ github.base_ref }}

      - name: Push - Checkout previous commit
        if: github.event_name == 'push'
        run: git checkout HEAD~1

      - name: Run benchmarks on original code
        run: make benchmark bench_o="-count=7" | tee previous.txt

      - name: Compare benchmarks
        run: benchstat previous.txt current.txt | tee benchstat.txt

      - name: Upload benchmark results
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results
          path: |
            current.txt
            previous.txt
            benchstat.txt

      - name: Build summary
        run: |
          echo "## Benchmark Comparison" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          cat benchstat.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

      - name: Detect regressions
        run: |
          # Return to the original branch/commit !
          git -c advice.detachedHead=false checkout - >/dev/null && \
            cat benchstat.txt | go run .tools/benchmark_regression_checker.go 10.0
  
